2020-04-13 19:38:04,916 ERROR: Exception on /index [GET] [in /home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/bekjan/Univer/python/microblog/app/routes.py", line 22, in index
    page = request.args('page', 1, type=int)
TypeError: 'ImmutableMultiDict' object is not callable
2020-04-13 22:40:31,756 INFO: Microblog startup [in /home/bekjan/Univer/python/microblog/app/__init__.py:42]
2020-04-14 17:00:16,408 INFO: Microblog startup [in /home/bekjan/Univer/python/microblog/app/__init__.py:42]
2020-04-14 17:00:38,911 INFO: Microblog startup [in /home/bekjan/Univer/python/microblog/app/__init__.py:42]
2020-04-14 22:37:50,454 INFO: Microblog startup [in /home/bekjan/Univer/python/microblog/app/__init__.py:44]
2020-04-15 01:14:00,213 INFO: Microblog startup [in /home/bekjan/Univer/python/microblog/app/__init__.py:44]
2020-04-15 01:14:13,182 INFO: Microblog startup [in /home/bekjan/Univer/python/microblog/app/__init__.py:44]
2020-04-15 01:17:11,252 INFO: Microblog startup [in /home/bekjan/Univer/python/microblog/app/__init__.py:44]
2020-04-15 01:17:38,571 ERROR: Exception on /register [POST] [in /home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bekjan/Univer/python/microblog/app/routes.py", line 80, in register
    if form.validate_on_submit():
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 100, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
TypeError: validate_username() takes 1 positional argument but 2 were given
2020-04-15 01:24:01,414 INFO: Microblog startup [in /home/bekjan/Univer/python/microblog/app/__init__.py:44]
2020-04-15 18:08:03,288 INFO: Microblog startup [in /home/bekjan/Univer/python/microblog/app/__init__.py:46]
2020-04-15 18:08:20,540 INFO: Microblog startup [in /home/bekjan/Univer/python/microblog/app/__init__.py:46]
2020-04-15 18:08:27,989 ERROR: Exception on / [GET] [in /home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/bekjan/Univer/python/microblog/app/routes.py", line 28, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items,
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/bekjan/Univer/python/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/bekjan/Univer/python/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends bootstrap/base.html %}
  File "/home/bekjan/Univer/python/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'base' is undefined
